# 🧠 Pandas MultiIndex & Multi-Level Columns


This notebook demonstrates how to use **MultiIndex** (multi-level indexing) in both rows and columns in `pandas`.

Multi-level indexing allows hierarchical organization of data, making it easier to work with panel-like data structures, grouped data, and advanced slicing/grouping operations.

## 🔹 Creating a MultiIndex DataFrame (Rows & Columns)

In [18]:
import pandas as pd
import numpy as np

# Multi-level row index
arrays = [
    ['2023', '2023', '2024', '2024'],
    ['Q1', 'Q2', 'Q1', 'Q2']
]
index = pd.MultiIndex.from_arrays(arrays, names=['Year', 'Quarter'])

# Multi-level column index
cols = pd.MultiIndex.from_tuples([
    ('Revenue', 'Product A'),
    ('Revenue', 'Product B'),
    ('Cost', 'Product A'),
    ('Cost', 'Product B'),
])

data = np.random.randint(100, 500, size=(4, 4))
df = pd.DataFrame(data, index=index, columns=cols)
df

               Revenue                Cost
             Product A Product B Product A Product B
Year Quarter
2023 Q1            113       319       465       330
     Q2            392       365       237       217
2024 Q1            108       446       349       429
     Q2            210       342       282       192

## 🔹 Slicing MultiIndex Rows

In [19]:
# Select all data for 2023
df.loc['2023']

          Revenue                Cost
        Product A Product B Product A Product B
Quarter
Q1            113       319       465       330
Q2            392       365       237       217

In [20]:
# Select specific year/quarter
df.loc[('2024', 'Q2')]

Revenue  Product A    210
         Product B    342
Cost     Product A    282
         Product B    192
Name: (2024, Q2), dtype: int32

In [21]:
# Slice across multiple levels
df.loc[('2023',), :]  # Same as above

          Revenue                Cost
        Product A Product B Product A Product B
Quarter
Q1            113       319       465       330
Q2            392       365       237       217

## 🔹 Working with MultiIndex Columns

In [22]:
# Select all Revenue columns
df['Revenue']

              Product A  Product B
Year Quarter
2023 Q1             113        319
     Q2             392        365
2024 Q1             108        446
     Q2             210        342

In [23]:
# Select Revenue for Product A
df['Revenue', 'Product A']

Year  Quarter
2023  Q1         113
      Q2         392
2024  Q1         108
      Q2         210
Name: (Revenue, Product A), dtype: int32

In [24]:
# Cross-section using .xs
df.xs('Product A', level=1, axis=1)   # All metrics for Product A

              Revenue  Cost
Year Quarter
2023 Q1           113   465
     Q2           392   237
2024 Q1           108   349
     Q2           210   282

In [25]:
df.xs(('2024', 'Q2'), level=('Year', 'Quarter'))

               Revenue                Cost
             Product A Product B Product A Product B
Year Quarter
2024 Q2            210       342       282       192

## 🔹 Sorting, Swapping & Resetting MultiIndex

In [26]:
# Swap index levels
df_swapped = df.swaplevel()
df_swapped.sort_index()

               Revenue                Cost
             Product A Product B Product A Product B
Quarter Year
Q1      2023       113       319       465       330
        2024       108       446       349       429
Q2      2023       392       365       237       217
        2024       210       342       282       192

In [27]:
# Sort index explicitly
df.sort_index(level='Quarter', ascending=False)

               Revenue                Cost
             Product A Product B Product A Product B
Year Quarter
2024 Q2            210       342       282       192
2023 Q2            392       365       237       217
2024 Q1            108       446       349       429
2023 Q1            113       319       465       330

In [28]:
# Reset one or all levels
df.reset_index(level='Quarter')

     Quarter   Revenue                Cost
             Product A Product B Product A Product B
Year
2023      Q1       113       319       465       330
2023      Q2       392       365       237       217
2024      Q1       108       446       349       429
2024      Q2       210       342       282       192

In [29]:
df.reset_index()

   Year Quarter   Revenue                Cost
                Product A Product B Product A Product B
0  2023      Q1       113       319       465       330
1  2023      Q2       392       365       237       217
2  2024      Q1       108       446       349       429
3  2024      Q2       210       342       282       192

## 🔹 GroupBy with MultiIndex

In [31]:
# Group by year and aggregate
df.groupby(level='Year').mean()

       Revenue                Cost
     Product A Product B Product A Product B
Year
2023     252.5     342.0     351.0     273.5
2024     159.0     394.0     315.5     310.5

In [32]:
# You can also group by a column level (on axis=1)
df.groupby(level=0, axis=1).sum()  # Sum by 'Revenue' and 'Cost'

C:\Users\yaqb9\AppData\Local\Temp\ipykernel_3320\489606827.py:2: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  df.groupby(level=0, axis=1).sum()  # Sum by 'Revenue' and 'Cost'

              Cost  Revenue
Year Quarter
2023 Q1        795      432
     Q2        454      757
2024 Q1        778      554
     Q2        474      552

## ✅ Summary


- MultiIndex enables hierarchical indexing for both rows and columns.
- Use `.loc[]` and `.xs()` for complex selections.
- Combine with `groupby()`, `swaplevel()`, and `sort_index()` for powerful data manipulation.